config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :posts
    resources :comments
    resources :likes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
	}
 	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: {
   thumb: '100x100>',
   square: '200x200#',
   medium: '300x300>'
 }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :bio, :avatar, :avatar_file_name])
    devise_parameter_sanitizer.permit(:account_update)
  end

  def after_sign_out_path_for(resource_or_scope)
    user_session_url
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @user = current_user
    @post = current_user.posts.new
  end

  def create
    post = Post.new(post_params)
    current_user.posts << post
    current_user.save
    p "YOU MADE IT: #{@current_user.posts}"
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @users = User.all
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checkoutmygreatsnapsgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if current_user %>
      <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h2>Post your snap!</h2>
<%= form_for :post, url: {controller: "posts", action: "create"} do |form| %>
  <p><%= form.label :description, "What is this?" %>
    <%= form.text_field :description %>
  </p>
  <p>
  	<%= form.file_field :image %>
	</p>
  <%= form.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <h2>Your profile</h2>
  <p><%= @user.username %></p>
  <div><%= image_tag(@user.avatar.url(:thumb)) %></div>
  <p><%= @user.bio %></p>
  <p><%= link_to "Post a new snap", new_user_post_url(current_user) %></p>

  <div>
    <h3>Your photos</h3>
    <% if @user.posts %>
      <% @user.posts.each do |post| %>
        <%= image_tag(post.image.url(:square)) %>
        <%= post.description %>
        posted at: <%= post.created_at %>
      <% end %>
    <% end %>
  </div>
</div>